# TODO: create github action configuration https://github.com/codecov/codecov-action
name: Upload code coverage to Codecov
on: [ push ]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run tests and simulate coverage report
        run: |
          pip install -r ./tests/requirements.txt
          cd ./tests
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./tests/coverage.xml
          flags: unittests
          fail_ci_if_error: true
